#../user_design_axi/rtl/mig_7series_vivado.v
#../user_design_axi/rtl/mig_7series_vivado_mig.v
../user_design_axi/rtl/mig_7series_vivado_mig_sim.v

../user_design_axi/rtl/clocking/mig_7series_v4_1_clk_ibuf.v
../user_design_axi/rtl/clocking/mig_7series_v4_1_infrastructure.v
../user_design_axi/rtl/clocking/mig_7series_v4_1_iodelay_ctrl.v
../user_design_axi/rtl/clocking/mig_7series_v4_1_tempmon.v

../user_design_axi/rtl/axi/mig_7series_v4_1_axi_ctrl_addr_decode.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_ctrl_read.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_ctrl_reg.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_ctrl_reg_bank.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_ctrl_top.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_ctrl_write.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc_ar_channel.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc_aw_channel.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc_b_channel.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc_cmd_arbiter.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc_cmd_fsm.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc_cmd_translator.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc_fifo.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc_incr_cmd.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc_r_channel.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc_simple_fifo.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc_w_channel.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc_wr_cmd_fsm.v
../user_design_axi/rtl/axi/mig_7series_v4_1_axi_mc_wrap_cmd.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_a_upsizer.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_axi_register_slice.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_axi_upsizer.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_axic_register_slice.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_carry_and.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_carry_latch_and.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_carry_latch_or.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_carry_or.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_command_fifo.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_comparator.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_comparator_sel.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_comparator_sel_static.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_r_upsizer.v
../user_design_axi/rtl/axi/mig_7series_v4_1_ddr_w_upsizer.v

../user_design_axi/rtl/controller/mig_7series_v4_1_arb_mux.v
../user_design_axi/rtl/controller/mig_7series_v4_1_arb_row_col.v
../user_design_axi/rtl/controller/mig_7series_v4_1_arb_select.v
../user_design_axi/rtl/controller/mig_7series_v4_1_bank_cntrl.v
../user_design_axi/rtl/controller/mig_7series_v4_1_bank_common.v
../user_design_axi/rtl/controller/mig_7series_v4_1_bank_compare.v
../user_design_axi/rtl/controller/mig_7series_v4_1_bank_mach.v
../user_design_axi/rtl/controller/mig_7series_v4_1_bank_queue.v
../user_design_axi/rtl/controller/mig_7series_v4_1_bank_state.v
../user_design_axi/rtl/controller/mig_7series_v4_1_col_mach.v
../user_design_axi/rtl/controller/mig_7series_v4_1_mc.v
../user_design_axi/rtl/controller/mig_7series_v4_1_rank_cntrl.v
../user_design_axi/rtl/controller/mig_7series_v4_1_rank_common.v
../user_design_axi/rtl/controller/mig_7series_v4_1_rank_mach.v
../user_design_axi/rtl/controller/mig_7series_v4_1_round_robin_arb.v

../user_design_axi/rtl/ecc/mig_7series_v4_1_ecc_buf.v
../user_design_axi/rtl/ecc/mig_7series_v4_1_ecc_dec_fix.v
../user_design_axi/rtl/ecc/mig_7series_v4_1_ecc_gen.v
../user_design_axi/rtl/ecc/mig_7series_v4_1_ecc_merge_enc.v
../user_design_axi/rtl/ecc/mig_7series_v4_1_fi_xor.v

../user_design_axi/rtl/ip_top/mig_7series_v4_1_mem_intfc.v
../user_design_axi/rtl/ip_top/mig_7series_v4_1_memc_ui_top_axi.v
../user_design_axi/rtl/ip_top/mig_7series_v4_1_memc_ui_top_std.v

../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_byte_group_io.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_byte_lane.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_calib_top.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_if_post_fifo.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_mc_phy.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_mc_phy_wrapper.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_of_pre_fifo.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_4lanes.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_ck_addr_cmd_delay.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_dqs_found_cal.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_dqs_found_cal_hr.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_init.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_cntlr.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_data.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_edge.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_lim.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_mux.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_po_cntlr.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_samp.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_oclkdelay_cal.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_prbs_rdlvl.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_rdlvl.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_tempmon.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_top.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_wrcal.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_wrlvl.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_phy_wrlvl_off_delay.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_prbs_gen.v
../user_design_axi/rtl/phy/mig_7series_v4_1_ddr_skip_calib_tap.v
../user_design_axi/rtl/phy/mig_7series_v4_1_poc_cc.v
../user_design_axi/rtl/phy/mig_7series_v4_1_poc_edge_store.v
../user_design_axi/rtl/phy/mig_7series_v4_1_poc_meta.v
../user_design_axi/rtl/phy/mig_7series_v4_1_poc_pd.v
../user_design_axi/rtl/phy/mig_7series_v4_1_poc_tap_base.v
../user_design_axi/rtl/phy/mig_7series_v4_1_poc_top.v

../user_design_axi/rtl/ui/mig_7series_v4_1_ui_cmd.v
../user_design_axi/rtl/ui/mig_7series_v4_1_ui_rd_data.v
../user_design_axi/rtl/ui/mig_7series_v4_1_ui_top.v
../user_design_axi/rtl/ui/mig_7series_v4_1_ui_wr_data.v

../example_design/sim/ddr3_model.v
../example_design/sim/glbl.v
../example_design/sim/wiredly.v

../example_design/rtl/rtl_axi_0907/NN_ASIC_core_32pe.v
../example_design/rtl/rtl_axi_0907/NN_ASIC_soc.v
../example_design/rtl/rtl_axi_0907/define.v
../example_design/rtl/rtl_axi_0907/neuron_leader.v
../example_design/rtl/rtl_axi_0907/neuron_worker.v
../example_design/rtl/rtl_axi_0907/ok_for_nnic.v
../example_design/rtl/rtl_axi_0907/ok_for_nnic_tb.v

../example_design/sim/oksim/okWireOR.v
../example_design/sim/oksim/okWireIn.v
../example_design/sim/oksim/okWireOut.v
../example_design/sim/oksim/okPipeOut.v
../example_design/sim/oksim/okRegisterBridge.v
../example_design/sim/oksim/okTriggerIn.v
../example_design/sim/oksim/okPipeIn.v
../example_design/sim/oksim/okBTPipeOut.v
../example_design/sim/oksim/okBTPipeIn.v
../example_design/sim/oksim/okTriggerOut.v
../example_design/sim/oksim/okHost.v

../example_design/ip_vivado/blk_mem_32_to_128/blk_mem_32_to_128_sim_netlist.v
../example_design/ip_vivado/blk_mem_256_to_128/blk_mem_256_to_128_sim_netlist.v
../example_design/ip_vivado/blk_mem_128_to_8/blk_mem_128_to_8_sim_netlist.v
../example_design/ip_vivado/blk_mem_128_to_8_out/blk_mem_128_to_8_out_sim_netlist.v
../example_design/ip_vivado/blk_mem_8_to_8/blk_mem_8_to_8_sim_netlist.v
../example_design/ip_vivado/ram_cfg/ram_cfg_sim_netlist.v
../example_design/ip_vivado/ram_4/ram_4_sim_netlist.v

